#how to print 

print ("akhil")


# performing a operation with out using a variable
print(2**2),print(3+3)


# with using a variable
num1=1
num2=2

print(num1*num2 )
print(num1**num2 )
print(num1+num2)  
print(num1-num2)
print(num1/num2)
print(num1//num2)
print(num1%num2)

# how to find the len of singring
name="akhil"
print(len(name))

# chnaging a variable value and then find the which value will be printed
a=9
a="akki"
print(a)
print(len(a))
print(a[0])

#indexing 
name="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
print(name[0])##A
print(name(1))##B


# slicing finding a  specific  length
name="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
print(len(name))
print(a[0:5])  
